- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

    

- name: Create Job - "{{DIR}}/{{COMPONENT}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{DIR}}/{{COMPONENT}}"
    url: http://172.31.83.253:8080
    user: admin
    password: "{{jenkins_password}}"