- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
    

- name: Create Job 
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.component}}"
    url: http://172.31.83.253:8080
    user: admin
    password: "{{jenkins_password}}"